name = "yomi-calendar-share"
main = "server/cloudflare/worker.ts"
compatibility_date = "2026-05-30"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "yomi-calendar-share-db"
database_id = "c2d6cf22-5bc6-48c9-961b-a4b592a150f2"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "yomi-calendar-share-images"
